allowed-teams:
  - isovalent

triggers:
  /test:
    workflows:
    - enterprise-clustermesh-mixed-routing.yaml
    - enterprise-clustermesh-overlapping-podcidr.yaml
    - enterprise-fqdn-ha.yaml
    - enterprise-fqdn-ha-upgrade.yaml
    - enterprise-multi-network.yaml
    - enterprise-srv6-datapath.yaml
    - enterprise-multicast.yaml
    - enterprise-conformance-cilium-mesh.yaml
  /ci-clustermesh:
    workflows:
    - enterprise-clustermesh-mixed-routing.yaml
    - enterprise-clustermesh-overlapping-podcidr.yaml
  # `(.+)` is regex capture group that is used as `extra-args` inputs parameter in the CuTE workflow
  # For example: `/cute bloomberg` or `/cute form3/MAKS`
  /cute (.+):
    workflows:
    - enterprise-cute.yaml
  /ci-multi-network:
    workflows:
    - enterprise-multi-network.yaml
  /ci-fqdn-ha:
    workflows:
    - enterprise-fqdn-ha.yaml
  /ci-fqdn-ha-upgrade:
    workflows:
    - enterprise-fqdn-ha-upgrade.yaml
  /ci-srv6-datapath:
    workflows:
    - enterprise-srv6-datapath.yaml
  /ci-cilium-mesh:
    workflows:
    - enterprise-conformance-cilium-mesh.yaml
  /ci-multicast:
    workflows:
    - enterprise-multicast.yaml

workflows:
  enterprise-clustermesh-mixed-routing.yaml:
    paths-ignore-regex: (test|Documentation)/
  enterprise-clustermesh-overlapping-podcidr.yaml:
    paths-ignore-regex: (test|Documentation)/
  enterprise-fqdn-ha.yaml:
    paths-ignore-regex: (test|Documentation)/
  enterprise-fqdn-ha-upgrade.yaml:
    paths-ignore-regex: (test|Documentation)/
  enterprise-multi-network.yaml:
    paths-ignore-regex: (test|Documentation)/
  enterprise-srv6-datapath.yaml:
    paths-ignore-regex: Documentation/
  enterprise-conformance-cilium-mesh.yaml:
    paths-ignore-regex: (test|Documentation)/
  enterprise-multicast.yaml:
    paths-ignore-regex: (test|Documentation)/
