{{- if and .Values.hubble.rbac.enabled .Values.hubble.rbac.policy.configMap.create }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.hubble.rbac.policy.configMap.name }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.hubble.relay.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    k8s-app: hubble-relay
    app.kubernetes.io/name: hubble-relay
    app.kubernetes.io/part-of: cilium
data:
  {{ .Values.hubble.rbac.policy.configMap.key }}: |
    roles: {{ toYaml .Values.hubble.rbac.policy.configMap.roles | nindent 6 }}
    bindings: {{ toYaml .Values.hubble.rbac.policy.configMap.bindings | nindent 6 }}
{{- end }}
