// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeIsovalentMeshEndpoints implements IsovalentMeshEndpointInterface
type FakeIsovalentMeshEndpoints struct {
	Fake *FakeIsovalentV1alpha1
	ns   string
}

var isovalentmeshendpointsResource = v1alpha1.SchemeGroupVersion.WithResource("isovalentmeshendpoints")

var isovalentmeshendpointsKind = v1alpha1.SchemeGroupVersion.WithKind("IsovalentMeshEndpoint")

// Get takes name of the isovalentMeshEndpoint, and returns the corresponding isovalentMeshEndpoint object, and an error if there is any.
func (c *FakeIsovalentMeshEndpoints) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IsovalentMeshEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(isovalentmeshendpointsResource, c.ns, name), &v1alpha1.IsovalentMeshEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IsovalentMeshEndpoint), err
}

// List takes label and field selectors, and returns the list of IsovalentMeshEndpoints that match those selectors.
func (c *FakeIsovalentMeshEndpoints) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IsovalentMeshEndpointList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(isovalentmeshendpointsResource, isovalentmeshendpointsKind, c.ns, opts), &v1alpha1.IsovalentMeshEndpointList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.IsovalentMeshEndpointList{ListMeta: obj.(*v1alpha1.IsovalentMeshEndpointList).ListMeta}
	for _, item := range obj.(*v1alpha1.IsovalentMeshEndpointList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested isovalentMeshEndpoints.
func (c *FakeIsovalentMeshEndpoints) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(isovalentmeshendpointsResource, c.ns, opts))

}

// Create takes the representation of a isovalentMeshEndpoint and creates it.  Returns the server's representation of the isovalentMeshEndpoint, and an error, if there is any.
func (c *FakeIsovalentMeshEndpoints) Create(ctx context.Context, isovalentMeshEndpoint *v1alpha1.IsovalentMeshEndpoint, opts v1.CreateOptions) (result *v1alpha1.IsovalentMeshEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(isovalentmeshendpointsResource, c.ns, isovalentMeshEndpoint), &v1alpha1.IsovalentMeshEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IsovalentMeshEndpoint), err
}

// Update takes the representation of a isovalentMeshEndpoint and updates it. Returns the server's representation of the isovalentMeshEndpoint, and an error, if there is any.
func (c *FakeIsovalentMeshEndpoints) Update(ctx context.Context, isovalentMeshEndpoint *v1alpha1.IsovalentMeshEndpoint, opts v1.UpdateOptions) (result *v1alpha1.IsovalentMeshEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(isovalentmeshendpointsResource, c.ns, isovalentMeshEndpoint), &v1alpha1.IsovalentMeshEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IsovalentMeshEndpoint), err
}

// Delete takes name of the isovalentMeshEndpoint and deletes it. Returns an error if one occurs.
func (c *FakeIsovalentMeshEndpoints) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(isovalentmeshendpointsResource, c.ns, name, opts), &v1alpha1.IsovalentMeshEndpoint{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIsovalentMeshEndpoints) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(isovalentmeshendpointsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.IsovalentMeshEndpointList{})
	return err
}

// Patch applies the patch and returns the patched isovalentMeshEndpoint.
func (c *FakeIsovalentMeshEndpoints) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IsovalentMeshEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(isovalentmeshendpointsResource, c.ns, name, pt, data, subresources...), &v1alpha1.IsovalentMeshEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IsovalentMeshEndpoint), err
}
