// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeIsovalentBFDNodeConfigOverrides implements IsovalentBFDNodeConfigOverrideInterface
type FakeIsovalentBFDNodeConfigOverrides struct {
	Fake *FakeIsovalentV1alpha1
}

var isovalentbfdnodeconfigoverridesResource = v1alpha1.SchemeGroupVersion.WithResource("isovalentbfdnodeconfigoverrides")

var isovalentbfdnodeconfigoverridesKind = v1alpha1.SchemeGroupVersion.WithKind("IsovalentBFDNodeConfigOverride")

// Get takes name of the isovalentBFDNodeConfigOverride, and returns the corresponding isovalentBFDNodeConfigOverride object, and an error if there is any.
func (c *FakeIsovalentBFDNodeConfigOverrides) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IsovalentBFDNodeConfigOverride, err error) {
	emptyResult := &v1alpha1.IsovalentBFDNodeConfigOverride{}
	obj, err := c.Fake.
		Invokes(testing.NewRootGetActionWithOptions(isovalentbfdnodeconfigoverridesResource, name, options), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.IsovalentBFDNodeConfigOverride), err
}

// List takes label and field selectors, and returns the list of IsovalentBFDNodeConfigOverrides that match those selectors.
func (c *FakeIsovalentBFDNodeConfigOverrides) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IsovalentBFDNodeConfigOverrideList, err error) {
	emptyResult := &v1alpha1.IsovalentBFDNodeConfigOverrideList{}
	obj, err := c.Fake.
		Invokes(testing.NewRootListActionWithOptions(isovalentbfdnodeconfigoverridesResource, isovalentbfdnodeconfigoverridesKind, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.IsovalentBFDNodeConfigOverrideList{ListMeta: obj.(*v1alpha1.IsovalentBFDNodeConfigOverrideList).ListMeta}
	for _, item := range obj.(*v1alpha1.IsovalentBFDNodeConfigOverrideList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested isovalentBFDNodeConfigOverrides.
func (c *FakeIsovalentBFDNodeConfigOverrides) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchActionWithOptions(isovalentbfdnodeconfigoverridesResource, opts))
}

// Create takes the representation of a isovalentBFDNodeConfigOverride and creates it.  Returns the server's representation of the isovalentBFDNodeConfigOverride, and an error, if there is any.
func (c *FakeIsovalentBFDNodeConfigOverrides) Create(ctx context.Context, isovalentBFDNodeConfigOverride *v1alpha1.IsovalentBFDNodeConfigOverride, opts v1.CreateOptions) (result *v1alpha1.IsovalentBFDNodeConfigOverride, err error) {
	emptyResult := &v1alpha1.IsovalentBFDNodeConfigOverride{}
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateActionWithOptions(isovalentbfdnodeconfigoverridesResource, isovalentBFDNodeConfigOverride, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.IsovalentBFDNodeConfigOverride), err
}

// Update takes the representation of a isovalentBFDNodeConfigOverride and updates it. Returns the server's representation of the isovalentBFDNodeConfigOverride, and an error, if there is any.
func (c *FakeIsovalentBFDNodeConfigOverrides) Update(ctx context.Context, isovalentBFDNodeConfigOverride *v1alpha1.IsovalentBFDNodeConfigOverride, opts v1.UpdateOptions) (result *v1alpha1.IsovalentBFDNodeConfigOverride, err error) {
	emptyResult := &v1alpha1.IsovalentBFDNodeConfigOverride{}
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateActionWithOptions(isovalentbfdnodeconfigoverridesResource, isovalentBFDNodeConfigOverride, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.IsovalentBFDNodeConfigOverride), err
}

// Delete takes name of the isovalentBFDNodeConfigOverride and deletes it. Returns an error if one occurs.
func (c *FakeIsovalentBFDNodeConfigOverrides) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(isovalentbfdnodeconfigoverridesResource, name, opts), &v1alpha1.IsovalentBFDNodeConfigOverride{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIsovalentBFDNodeConfigOverrides) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionActionWithOptions(isovalentbfdnodeconfigoverridesResource, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.IsovalentBFDNodeConfigOverrideList{})
	return err
}

// Patch applies the patch and returns the patched isovalentBFDNodeConfigOverride.
func (c *FakeIsovalentBFDNodeConfigOverrides) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IsovalentBFDNodeConfigOverride, err error) {
	emptyResult := &v1alpha1.IsovalentBFDNodeConfigOverride{}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceActionWithOptions(isovalentbfdnodeconfigoverridesResource, name, pt, data, opts, subresources...), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.IsovalentBFDNodeConfigOverride), err
}
