// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type IsovalentFQDNGroupExpansion interface{}

type IsovalentMeshEndpointExpansion interface{}

type IsovalentMulticastGroupExpansion interface{}

type IsovalentMulticastNodeExpansion interface{}

type IsovalentPodNetworkExpansion interface{}

type IsovalentSRv6EgressPolicyExpansion interface{}

type IsovalentSRv6LocatorPoolExpansion interface{}

type IsovalentSRv6SIDManagerExpansion interface{}

type IsovalentVRFExpansion interface{}
