// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	scheme "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// IsovalentBGPAdvertisementsGetter has a method to return a IsovalentBGPAdvertisementInterface.
// A group's client should implement this interface.
type IsovalentBGPAdvertisementsGetter interface {
	IsovalentBGPAdvertisements() IsovalentBGPAdvertisementInterface
}

// IsovalentBGPAdvertisementInterface has methods to work with IsovalentBGPAdvertisement resources.
type IsovalentBGPAdvertisementInterface interface {
	Create(ctx context.Context, isovalentBGPAdvertisement *v1alpha1.IsovalentBGPAdvertisement, opts v1.CreateOptions) (*v1alpha1.IsovalentBGPAdvertisement, error)
	Update(ctx context.Context, isovalentBGPAdvertisement *v1alpha1.IsovalentBGPAdvertisement, opts v1.UpdateOptions) (*v1alpha1.IsovalentBGPAdvertisement, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.IsovalentBGPAdvertisement, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.IsovalentBGPAdvertisementList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IsovalentBGPAdvertisement, err error)
	IsovalentBGPAdvertisementExpansion
}

// isovalentBGPAdvertisements implements IsovalentBGPAdvertisementInterface
type isovalentBGPAdvertisements struct {
	client rest.Interface
}

// newIsovalentBGPAdvertisements returns a IsovalentBGPAdvertisements
func newIsovalentBGPAdvertisements(c *IsovalentV1alpha1Client) *isovalentBGPAdvertisements {
	return &isovalentBGPAdvertisements{
		client: c.RESTClient(),
	}
}

// Get takes name of the isovalentBGPAdvertisement, and returns the corresponding isovalentBGPAdvertisement object, and an error if there is any.
func (c *isovalentBGPAdvertisements) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IsovalentBGPAdvertisement, err error) {
	result = &v1alpha1.IsovalentBGPAdvertisement{}
	err = c.client.Get().
		Resource("isovalentbgpadvertisements").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of IsovalentBGPAdvertisements that match those selectors.
func (c *isovalentBGPAdvertisements) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IsovalentBGPAdvertisementList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.IsovalentBGPAdvertisementList{}
	err = c.client.Get().
		Resource("isovalentbgpadvertisements").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested isovalentBGPAdvertisements.
func (c *isovalentBGPAdvertisements) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("isovalentbgpadvertisements").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a isovalentBGPAdvertisement and creates it.  Returns the server's representation of the isovalentBGPAdvertisement, and an error, if there is any.
func (c *isovalentBGPAdvertisements) Create(ctx context.Context, isovalentBGPAdvertisement *v1alpha1.IsovalentBGPAdvertisement, opts v1.CreateOptions) (result *v1alpha1.IsovalentBGPAdvertisement, err error) {
	result = &v1alpha1.IsovalentBGPAdvertisement{}
	err = c.client.Post().
		Resource("isovalentbgpadvertisements").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(isovalentBGPAdvertisement).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a isovalentBGPAdvertisement and updates it. Returns the server's representation of the isovalentBGPAdvertisement, and an error, if there is any.
func (c *isovalentBGPAdvertisements) Update(ctx context.Context, isovalentBGPAdvertisement *v1alpha1.IsovalentBGPAdvertisement, opts v1.UpdateOptions) (result *v1alpha1.IsovalentBGPAdvertisement, err error) {
	result = &v1alpha1.IsovalentBGPAdvertisement{}
	err = c.client.Put().
		Resource("isovalentbgpadvertisements").
		Name(isovalentBGPAdvertisement.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(isovalentBGPAdvertisement).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the isovalentBGPAdvertisement and deletes it. Returns an error if one occurs.
func (c *isovalentBGPAdvertisements) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("isovalentbgpadvertisements").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *isovalentBGPAdvertisements) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("isovalentbgpadvertisements").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched isovalentBGPAdvertisement.
func (c *isovalentBGPAdvertisements) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IsovalentBGPAdvertisement, err error) {
	result = &v1alpha1.IsovalentBGPAdvertisement{}
	err = c.client.Patch(pt).
		Resource("isovalentbgpadvertisements").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
