// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	scheme "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// IsovalentBGPClusterConfigsGetter has a method to return a IsovalentBGPClusterConfigInterface.
// A group's client should implement this interface.
type IsovalentBGPClusterConfigsGetter interface {
	IsovalentBGPClusterConfigs() IsovalentBGPClusterConfigInterface
}

// IsovalentBGPClusterConfigInterface has methods to work with IsovalentBGPClusterConfig resources.
type IsovalentBGPClusterConfigInterface interface {
	Create(ctx context.Context, isovalentBGPClusterConfig *v1alpha1.IsovalentBGPClusterConfig, opts v1.CreateOptions) (*v1alpha1.IsovalentBGPClusterConfig, error)
	Update(ctx context.Context, isovalentBGPClusterConfig *v1alpha1.IsovalentBGPClusterConfig, opts v1.UpdateOptions) (*v1alpha1.IsovalentBGPClusterConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.IsovalentBGPClusterConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.IsovalentBGPClusterConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IsovalentBGPClusterConfig, err error)
	IsovalentBGPClusterConfigExpansion
}

// isovalentBGPClusterConfigs implements IsovalentBGPClusterConfigInterface
type isovalentBGPClusterConfigs struct {
	client rest.Interface
}

// newIsovalentBGPClusterConfigs returns a IsovalentBGPClusterConfigs
func newIsovalentBGPClusterConfigs(c *IsovalentV1alpha1Client) *isovalentBGPClusterConfigs {
	return &isovalentBGPClusterConfigs{
		client: c.RESTClient(),
	}
}

// Get takes name of the isovalentBGPClusterConfig, and returns the corresponding isovalentBGPClusterConfig object, and an error if there is any.
func (c *isovalentBGPClusterConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IsovalentBGPClusterConfig, err error) {
	result = &v1alpha1.IsovalentBGPClusterConfig{}
	err = c.client.Get().
		Resource("isovalentbgpclusterconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of IsovalentBGPClusterConfigs that match those selectors.
func (c *isovalentBGPClusterConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IsovalentBGPClusterConfigList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.IsovalentBGPClusterConfigList{}
	err = c.client.Get().
		Resource("isovalentbgpclusterconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested isovalentBGPClusterConfigs.
func (c *isovalentBGPClusterConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("isovalentbgpclusterconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a isovalentBGPClusterConfig and creates it.  Returns the server's representation of the isovalentBGPClusterConfig, and an error, if there is any.
func (c *isovalentBGPClusterConfigs) Create(ctx context.Context, isovalentBGPClusterConfig *v1alpha1.IsovalentBGPClusterConfig, opts v1.CreateOptions) (result *v1alpha1.IsovalentBGPClusterConfig, err error) {
	result = &v1alpha1.IsovalentBGPClusterConfig{}
	err = c.client.Post().
		Resource("isovalentbgpclusterconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(isovalentBGPClusterConfig).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a isovalentBGPClusterConfig and updates it. Returns the server's representation of the isovalentBGPClusterConfig, and an error, if there is any.
func (c *isovalentBGPClusterConfigs) Update(ctx context.Context, isovalentBGPClusterConfig *v1alpha1.IsovalentBGPClusterConfig, opts v1.UpdateOptions) (result *v1alpha1.IsovalentBGPClusterConfig, err error) {
	result = &v1alpha1.IsovalentBGPClusterConfig{}
	err = c.client.Put().
		Resource("isovalentbgpclusterconfigs").
		Name(isovalentBGPClusterConfig.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(isovalentBGPClusterConfig).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the isovalentBGPClusterConfig and deletes it. Returns an error if one occurs.
func (c *isovalentBGPClusterConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("isovalentbgpclusterconfigs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *isovalentBGPClusterConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("isovalentbgpclusterconfigs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched isovalentBGPClusterConfig.
func (c *isovalentBGPClusterConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IsovalentBGPClusterConfig, err error) {
	result = &v1alpha1.IsovalentBGPClusterConfig{}
	err = c.client.Patch(pt).
		Resource("isovalentbgpclusterconfigs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
