// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	scheme "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// IsovalentBGPNodeConfigOverridesGetter has a method to return a IsovalentBGPNodeConfigOverrideInterface.
// A group's client should implement this interface.
type IsovalentBGPNodeConfigOverridesGetter interface {
	IsovalentBGPNodeConfigOverrides() IsovalentBGPNodeConfigOverrideInterface
}

// IsovalentBGPNodeConfigOverrideInterface has methods to work with IsovalentBGPNodeConfigOverride resources.
type IsovalentBGPNodeConfigOverrideInterface interface {
	Create(ctx context.Context, isovalentBGPNodeConfigOverride *v1alpha1.IsovalentBGPNodeConfigOverride, opts v1.CreateOptions) (*v1alpha1.IsovalentBGPNodeConfigOverride, error)
	Update(ctx context.Context, isovalentBGPNodeConfigOverride *v1alpha1.IsovalentBGPNodeConfigOverride, opts v1.UpdateOptions) (*v1alpha1.IsovalentBGPNodeConfigOverride, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.IsovalentBGPNodeConfigOverride, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.IsovalentBGPNodeConfigOverrideList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IsovalentBGPNodeConfigOverride, err error)
	IsovalentBGPNodeConfigOverrideExpansion
}

// isovalentBGPNodeConfigOverrides implements IsovalentBGPNodeConfigOverrideInterface
type isovalentBGPNodeConfigOverrides struct {
	client rest.Interface
}

// newIsovalentBGPNodeConfigOverrides returns a IsovalentBGPNodeConfigOverrides
func newIsovalentBGPNodeConfigOverrides(c *IsovalentV1alpha1Client) *isovalentBGPNodeConfigOverrides {
	return &isovalentBGPNodeConfigOverrides{
		client: c.RESTClient(),
	}
}

// Get takes name of the isovalentBGPNodeConfigOverride, and returns the corresponding isovalentBGPNodeConfigOverride object, and an error if there is any.
func (c *isovalentBGPNodeConfigOverrides) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IsovalentBGPNodeConfigOverride, err error) {
	result = &v1alpha1.IsovalentBGPNodeConfigOverride{}
	err = c.client.Get().
		Resource("isovalentbgpnodeconfigoverrides").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of IsovalentBGPNodeConfigOverrides that match those selectors.
func (c *isovalentBGPNodeConfigOverrides) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IsovalentBGPNodeConfigOverrideList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.IsovalentBGPNodeConfigOverrideList{}
	err = c.client.Get().
		Resource("isovalentbgpnodeconfigoverrides").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested isovalentBGPNodeConfigOverrides.
func (c *isovalentBGPNodeConfigOverrides) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("isovalentbgpnodeconfigoverrides").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a isovalentBGPNodeConfigOverride and creates it.  Returns the server's representation of the isovalentBGPNodeConfigOverride, and an error, if there is any.
func (c *isovalentBGPNodeConfigOverrides) Create(ctx context.Context, isovalentBGPNodeConfigOverride *v1alpha1.IsovalentBGPNodeConfigOverride, opts v1.CreateOptions) (result *v1alpha1.IsovalentBGPNodeConfigOverride, err error) {
	result = &v1alpha1.IsovalentBGPNodeConfigOverride{}
	err = c.client.Post().
		Resource("isovalentbgpnodeconfigoverrides").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(isovalentBGPNodeConfigOverride).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a isovalentBGPNodeConfigOverride and updates it. Returns the server's representation of the isovalentBGPNodeConfigOverride, and an error, if there is any.
func (c *isovalentBGPNodeConfigOverrides) Update(ctx context.Context, isovalentBGPNodeConfigOverride *v1alpha1.IsovalentBGPNodeConfigOverride, opts v1.UpdateOptions) (result *v1alpha1.IsovalentBGPNodeConfigOverride, err error) {
	result = &v1alpha1.IsovalentBGPNodeConfigOverride{}
	err = c.client.Put().
		Resource("isovalentbgpnodeconfigoverrides").
		Name(isovalentBGPNodeConfigOverride.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(isovalentBGPNodeConfigOverride).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the isovalentBGPNodeConfigOverride and deletes it. Returns an error if one occurs.
func (c *isovalentBGPNodeConfigOverrides) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("isovalentbgpnodeconfigoverrides").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *isovalentBGPNodeConfigOverrides) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("isovalentbgpnodeconfigoverrides").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched isovalentBGPNodeConfigOverride.
func (c *isovalentBGPNodeConfigOverrides) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IsovalentBGPNodeConfigOverride, err error) {
	result = &v1alpha1.IsovalentBGPNodeConfigOverride{}
	err = c.client.Patch(pt).
		Resource("isovalentbgpnodeconfigoverrides").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
