// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	scheme "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// IsovalentBFDNodeConfigOverridesGetter has a method to return a IsovalentBFDNodeConfigOverrideInterface.
// A group's client should implement this interface.
type IsovalentBFDNodeConfigOverridesGetter interface {
	IsovalentBFDNodeConfigOverrides() IsovalentBFDNodeConfigOverrideInterface
}

// IsovalentBFDNodeConfigOverrideInterface has methods to work with IsovalentBFDNodeConfigOverride resources.
type IsovalentBFDNodeConfigOverrideInterface interface {
	Create(ctx context.Context, isovalentBFDNodeConfigOverride *v1alpha1.IsovalentBFDNodeConfigOverride, opts v1.CreateOptions) (*v1alpha1.IsovalentBFDNodeConfigOverride, error)
	Update(ctx context.Context, isovalentBFDNodeConfigOverride *v1alpha1.IsovalentBFDNodeConfigOverride, opts v1.UpdateOptions) (*v1alpha1.IsovalentBFDNodeConfigOverride, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.IsovalentBFDNodeConfigOverride, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.IsovalentBFDNodeConfigOverrideList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IsovalentBFDNodeConfigOverride, err error)
	IsovalentBFDNodeConfigOverrideExpansion
}

// isovalentBFDNodeConfigOverrides implements IsovalentBFDNodeConfigOverrideInterface
type isovalentBFDNodeConfigOverrides struct {
	client rest.Interface
}

// newIsovalentBFDNodeConfigOverrides returns a IsovalentBFDNodeConfigOverrides
func newIsovalentBFDNodeConfigOverrides(c *IsovalentV1alpha1Client) *isovalentBFDNodeConfigOverrides {
	return &isovalentBFDNodeConfigOverrides{
		client: c.RESTClient(),
	}
}

// Get takes name of the isovalentBFDNodeConfigOverride, and returns the corresponding isovalentBFDNodeConfigOverride object, and an error if there is any.
func (c *isovalentBFDNodeConfigOverrides) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IsovalentBFDNodeConfigOverride, err error) {
	result = &v1alpha1.IsovalentBFDNodeConfigOverride{}
	err = c.client.Get().
		Resource("isovalentbfdnodeconfigoverrides").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of IsovalentBFDNodeConfigOverrides that match those selectors.
func (c *isovalentBFDNodeConfigOverrides) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IsovalentBFDNodeConfigOverrideList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.IsovalentBFDNodeConfigOverrideList{}
	err = c.client.Get().
		Resource("isovalentbfdnodeconfigoverrides").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested isovalentBFDNodeConfigOverrides.
func (c *isovalentBFDNodeConfigOverrides) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("isovalentbfdnodeconfigoverrides").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a isovalentBFDNodeConfigOverride and creates it.  Returns the server's representation of the isovalentBFDNodeConfigOverride, and an error, if there is any.
func (c *isovalentBFDNodeConfigOverrides) Create(ctx context.Context, isovalentBFDNodeConfigOverride *v1alpha1.IsovalentBFDNodeConfigOverride, opts v1.CreateOptions) (result *v1alpha1.IsovalentBFDNodeConfigOverride, err error) {
	result = &v1alpha1.IsovalentBFDNodeConfigOverride{}
	err = c.client.Post().
		Resource("isovalentbfdnodeconfigoverrides").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(isovalentBFDNodeConfigOverride).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a isovalentBFDNodeConfigOverride and updates it. Returns the server's representation of the isovalentBFDNodeConfigOverride, and an error, if there is any.
func (c *isovalentBFDNodeConfigOverrides) Update(ctx context.Context, isovalentBFDNodeConfigOverride *v1alpha1.IsovalentBFDNodeConfigOverride, opts v1.UpdateOptions) (result *v1alpha1.IsovalentBFDNodeConfigOverride, err error) {
	result = &v1alpha1.IsovalentBFDNodeConfigOverride{}
	err = c.client.Put().
		Resource("isovalentbfdnodeconfigoverrides").
		Name(isovalentBFDNodeConfigOverride.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(isovalentBFDNodeConfigOverride).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the isovalentBFDNodeConfigOverride and deletes it. Returns an error if one occurs.
func (c *isovalentBFDNodeConfigOverrides) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("isovalentbfdnodeconfigoverrides").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *isovalentBFDNodeConfigOverrides) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("isovalentbfdnodeconfigoverrides").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched isovalentBFDNodeConfigOverride.
func (c *isovalentBFDNodeConfigOverrides) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IsovalentBFDNodeConfigOverride, err error) {
	result = &v1alpha1.IsovalentBFDNodeConfigOverride{}
	err = c.client.Patch(pt).
		Resource("isovalentbfdnodeconfigoverrides").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
