// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	scheme "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// IsovalentBGPNodeConfigsGetter has a method to return a IsovalentBGPNodeConfigInterface.
// A group's client should implement this interface.
type IsovalentBGPNodeConfigsGetter interface {
	IsovalentBGPNodeConfigs() IsovalentBGPNodeConfigInterface
}

// IsovalentBGPNodeConfigInterface has methods to work with IsovalentBGPNodeConfig resources.
type IsovalentBGPNodeConfigInterface interface {
	Create(ctx context.Context, isovalentBGPNodeConfig *v1alpha1.IsovalentBGPNodeConfig, opts v1.CreateOptions) (*v1alpha1.IsovalentBGPNodeConfig, error)
	Update(ctx context.Context, isovalentBGPNodeConfig *v1alpha1.IsovalentBGPNodeConfig, opts v1.UpdateOptions) (*v1alpha1.IsovalentBGPNodeConfig, error)
	UpdateStatus(ctx context.Context, isovalentBGPNodeConfig *v1alpha1.IsovalentBGPNodeConfig, opts v1.UpdateOptions) (*v1alpha1.IsovalentBGPNodeConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.IsovalentBGPNodeConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.IsovalentBGPNodeConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IsovalentBGPNodeConfig, err error)
	IsovalentBGPNodeConfigExpansion
}

// isovalentBGPNodeConfigs implements IsovalentBGPNodeConfigInterface
type isovalentBGPNodeConfigs struct {
	client rest.Interface
}

// newIsovalentBGPNodeConfigs returns a IsovalentBGPNodeConfigs
func newIsovalentBGPNodeConfigs(c *IsovalentV1alpha1Client) *isovalentBGPNodeConfigs {
	return &isovalentBGPNodeConfigs{
		client: c.RESTClient(),
	}
}

// Get takes name of the isovalentBGPNodeConfig, and returns the corresponding isovalentBGPNodeConfig object, and an error if there is any.
func (c *isovalentBGPNodeConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IsovalentBGPNodeConfig, err error) {
	result = &v1alpha1.IsovalentBGPNodeConfig{}
	err = c.client.Get().
		Resource("isovalentbgpnodeconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of IsovalentBGPNodeConfigs that match those selectors.
func (c *isovalentBGPNodeConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IsovalentBGPNodeConfigList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.IsovalentBGPNodeConfigList{}
	err = c.client.Get().
		Resource("isovalentbgpnodeconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested isovalentBGPNodeConfigs.
func (c *isovalentBGPNodeConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("isovalentbgpnodeconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a isovalentBGPNodeConfig and creates it.  Returns the server's representation of the isovalentBGPNodeConfig, and an error, if there is any.
func (c *isovalentBGPNodeConfigs) Create(ctx context.Context, isovalentBGPNodeConfig *v1alpha1.IsovalentBGPNodeConfig, opts v1.CreateOptions) (result *v1alpha1.IsovalentBGPNodeConfig, err error) {
	result = &v1alpha1.IsovalentBGPNodeConfig{}
	err = c.client.Post().
		Resource("isovalentbgpnodeconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(isovalentBGPNodeConfig).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a isovalentBGPNodeConfig and updates it. Returns the server's representation of the isovalentBGPNodeConfig, and an error, if there is any.
func (c *isovalentBGPNodeConfigs) Update(ctx context.Context, isovalentBGPNodeConfig *v1alpha1.IsovalentBGPNodeConfig, opts v1.UpdateOptions) (result *v1alpha1.IsovalentBGPNodeConfig, err error) {
	result = &v1alpha1.IsovalentBGPNodeConfig{}
	err = c.client.Put().
		Resource("isovalentbgpnodeconfigs").
		Name(isovalentBGPNodeConfig.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(isovalentBGPNodeConfig).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *isovalentBGPNodeConfigs) UpdateStatus(ctx context.Context, isovalentBGPNodeConfig *v1alpha1.IsovalentBGPNodeConfig, opts v1.UpdateOptions) (result *v1alpha1.IsovalentBGPNodeConfig, err error) {
	result = &v1alpha1.IsovalentBGPNodeConfig{}
	err = c.client.Put().
		Resource("isovalentbgpnodeconfigs").
		Name(isovalentBGPNodeConfig.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(isovalentBGPNodeConfig).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the isovalentBGPNodeConfig and deletes it. Returns an error if one occurs.
func (c *isovalentBGPNodeConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("isovalentbgpnodeconfigs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *isovalentBGPNodeConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("isovalentbgpnodeconfigs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched isovalentBGPNodeConfig.
func (c *isovalentBGPNodeConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IsovalentBGPNodeConfig, err error) {
	result = &v1alpha1.IsovalentBGPNodeConfig{}
	err = c.client.Patch(pt).
		Resource("isovalentbgpnodeconfigs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
