// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	scheme "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// IsovalentSRv6EgressPoliciesGetter has a method to return a IsovalentSRv6EgressPolicyInterface.
// A group's client should implement this interface.
type IsovalentSRv6EgressPoliciesGetter interface {
	IsovalentSRv6EgressPolicies() IsovalentSRv6EgressPolicyInterface
}

// IsovalentSRv6EgressPolicyInterface has methods to work with IsovalentSRv6EgressPolicy resources.
type IsovalentSRv6EgressPolicyInterface interface {
	Create(ctx context.Context, isovalentSRv6EgressPolicy *v1alpha1.IsovalentSRv6EgressPolicy, opts v1.CreateOptions) (*v1alpha1.IsovalentSRv6EgressPolicy, error)
	Update(ctx context.Context, isovalentSRv6EgressPolicy *v1alpha1.IsovalentSRv6EgressPolicy, opts v1.UpdateOptions) (*v1alpha1.IsovalentSRv6EgressPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.IsovalentSRv6EgressPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.IsovalentSRv6EgressPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IsovalentSRv6EgressPolicy, err error)
	IsovalentSRv6EgressPolicyExpansion
}

// isovalentSRv6EgressPolicies implements IsovalentSRv6EgressPolicyInterface
type isovalentSRv6EgressPolicies struct {
	client rest.Interface
}

// newIsovalentSRv6EgressPolicies returns a IsovalentSRv6EgressPolicies
func newIsovalentSRv6EgressPolicies(c *IsovalentV1alpha1Client) *isovalentSRv6EgressPolicies {
	return &isovalentSRv6EgressPolicies{
		client: c.RESTClient(),
	}
}

// Get takes name of the isovalentSRv6EgressPolicy, and returns the corresponding isovalentSRv6EgressPolicy object, and an error if there is any.
func (c *isovalentSRv6EgressPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IsovalentSRv6EgressPolicy, err error) {
	result = &v1alpha1.IsovalentSRv6EgressPolicy{}
	err = c.client.Get().
		Resource("isovalentsrv6egresspolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of IsovalentSRv6EgressPolicies that match those selectors.
func (c *isovalentSRv6EgressPolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IsovalentSRv6EgressPolicyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.IsovalentSRv6EgressPolicyList{}
	err = c.client.Get().
		Resource("isovalentsrv6egresspolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested isovalentSRv6EgressPolicies.
func (c *isovalentSRv6EgressPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("isovalentsrv6egresspolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a isovalentSRv6EgressPolicy and creates it.  Returns the server's representation of the isovalentSRv6EgressPolicy, and an error, if there is any.
func (c *isovalentSRv6EgressPolicies) Create(ctx context.Context, isovalentSRv6EgressPolicy *v1alpha1.IsovalentSRv6EgressPolicy, opts v1.CreateOptions) (result *v1alpha1.IsovalentSRv6EgressPolicy, err error) {
	result = &v1alpha1.IsovalentSRv6EgressPolicy{}
	err = c.client.Post().
		Resource("isovalentsrv6egresspolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(isovalentSRv6EgressPolicy).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a isovalentSRv6EgressPolicy and updates it. Returns the server's representation of the isovalentSRv6EgressPolicy, and an error, if there is any.
func (c *isovalentSRv6EgressPolicies) Update(ctx context.Context, isovalentSRv6EgressPolicy *v1alpha1.IsovalentSRv6EgressPolicy, opts v1.UpdateOptions) (result *v1alpha1.IsovalentSRv6EgressPolicy, err error) {
	result = &v1alpha1.IsovalentSRv6EgressPolicy{}
	err = c.client.Put().
		Resource("isovalentsrv6egresspolicies").
		Name(isovalentSRv6EgressPolicy.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(isovalentSRv6EgressPolicy).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the isovalentSRv6EgressPolicy and deletes it. Returns an error if one occurs.
func (c *isovalentSRv6EgressPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("isovalentsrv6egresspolicies").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *isovalentSRv6EgressPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("isovalentsrv6egresspolicies").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched isovalentSRv6EgressPolicy.
func (c *isovalentSRv6EgressPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IsovalentSRv6EgressPolicy, err error) {
	result = &v1alpha1.IsovalentSRv6EgressPolicy{}
	err = c.client.Patch(pt).
		Resource("isovalentsrv6egresspolicies").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
