// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	scheme "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// IsovalentBGPNodeConfigOverridesGetter has a method to return a IsovalentBGPNodeConfigOverrideInterface.
// A group's client should implement this interface.
type IsovalentBGPNodeConfigOverridesGetter interface {
	IsovalentBGPNodeConfigOverrides() IsovalentBGPNodeConfigOverrideInterface
}

// IsovalentBGPNodeConfigOverrideInterface has methods to work with IsovalentBGPNodeConfigOverride resources.
type IsovalentBGPNodeConfigOverrideInterface interface {
	Create(ctx context.Context, isovalentBGPNodeConfigOverride *v1alpha1.IsovalentBGPNodeConfigOverride, opts v1.CreateOptions) (*v1alpha1.IsovalentBGPNodeConfigOverride, error)
	Update(ctx context.Context, isovalentBGPNodeConfigOverride *v1alpha1.IsovalentBGPNodeConfigOverride, opts v1.UpdateOptions) (*v1alpha1.IsovalentBGPNodeConfigOverride, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.IsovalentBGPNodeConfigOverride, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.IsovalentBGPNodeConfigOverrideList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IsovalentBGPNodeConfigOverride, err error)
	IsovalentBGPNodeConfigOverrideExpansion
}

// isovalentBGPNodeConfigOverrides implements IsovalentBGPNodeConfigOverrideInterface
type isovalentBGPNodeConfigOverrides struct {
	*gentype.ClientWithList[*v1alpha1.IsovalentBGPNodeConfigOverride, *v1alpha1.IsovalentBGPNodeConfigOverrideList]
}

// newIsovalentBGPNodeConfigOverrides returns a IsovalentBGPNodeConfigOverrides
func newIsovalentBGPNodeConfigOverrides(c *IsovalentV1alpha1Client) *isovalentBGPNodeConfigOverrides {
	return &isovalentBGPNodeConfigOverrides{
		gentype.NewClientWithList[*v1alpha1.IsovalentBGPNodeConfigOverride, *v1alpha1.IsovalentBGPNodeConfigOverrideList](
			"isovalentbgpnodeconfigoverrides",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v1alpha1.IsovalentBGPNodeConfigOverride { return &v1alpha1.IsovalentBGPNodeConfigOverride{} },
			func() *v1alpha1.IsovalentBGPNodeConfigOverrideList {
				return &v1alpha1.IsovalentBGPNodeConfigOverrideList{}
			}),
	}
}
