// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	scheme "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// IsovalentMeshEndpointsGetter has a method to return a IsovalentMeshEndpointInterface.
// A group's client should implement this interface.
type IsovalentMeshEndpointsGetter interface {
	IsovalentMeshEndpoints(namespace string) IsovalentMeshEndpointInterface
}

// IsovalentMeshEndpointInterface has methods to work with IsovalentMeshEndpoint resources.
type IsovalentMeshEndpointInterface interface {
	Create(ctx context.Context, isovalentMeshEndpoint *v1alpha1.IsovalentMeshEndpoint, opts v1.CreateOptions) (*v1alpha1.IsovalentMeshEndpoint, error)
	Update(ctx context.Context, isovalentMeshEndpoint *v1alpha1.IsovalentMeshEndpoint, opts v1.UpdateOptions) (*v1alpha1.IsovalentMeshEndpoint, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.IsovalentMeshEndpoint, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.IsovalentMeshEndpointList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IsovalentMeshEndpoint, err error)
	IsovalentMeshEndpointExpansion
}

// isovalentMeshEndpoints implements IsovalentMeshEndpointInterface
type isovalentMeshEndpoints struct {
	client rest.Interface
	ns     string
}

// newIsovalentMeshEndpoints returns a IsovalentMeshEndpoints
func newIsovalentMeshEndpoints(c *IsovalentV1alpha1Client, namespace string) *isovalentMeshEndpoints {
	return &isovalentMeshEndpoints{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the isovalentMeshEndpoint, and returns the corresponding isovalentMeshEndpoint object, and an error if there is any.
func (c *isovalentMeshEndpoints) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IsovalentMeshEndpoint, err error) {
	result = &v1alpha1.IsovalentMeshEndpoint{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("isovalentmeshendpoints").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of IsovalentMeshEndpoints that match those selectors.
func (c *isovalentMeshEndpoints) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IsovalentMeshEndpointList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.IsovalentMeshEndpointList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("isovalentmeshendpoints").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested isovalentMeshEndpoints.
func (c *isovalentMeshEndpoints) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("isovalentmeshendpoints").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a isovalentMeshEndpoint and creates it.  Returns the server's representation of the isovalentMeshEndpoint, and an error, if there is any.
func (c *isovalentMeshEndpoints) Create(ctx context.Context, isovalentMeshEndpoint *v1alpha1.IsovalentMeshEndpoint, opts v1.CreateOptions) (result *v1alpha1.IsovalentMeshEndpoint, err error) {
	result = &v1alpha1.IsovalentMeshEndpoint{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("isovalentmeshendpoints").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(isovalentMeshEndpoint).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a isovalentMeshEndpoint and updates it. Returns the server's representation of the isovalentMeshEndpoint, and an error, if there is any.
func (c *isovalentMeshEndpoints) Update(ctx context.Context, isovalentMeshEndpoint *v1alpha1.IsovalentMeshEndpoint, opts v1.UpdateOptions) (result *v1alpha1.IsovalentMeshEndpoint, err error) {
	result = &v1alpha1.IsovalentMeshEndpoint{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("isovalentmeshendpoints").
		Name(isovalentMeshEndpoint.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(isovalentMeshEndpoint).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the isovalentMeshEndpoint and deletes it. Returns an error if one occurs.
func (c *isovalentMeshEndpoints) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("isovalentmeshendpoints").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *isovalentMeshEndpoints) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("isovalentmeshendpoints").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched isovalentMeshEndpoint.
func (c *isovalentMeshEndpoints) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IsovalentMeshEndpoint, err error) {
	result = &v1alpha1.IsovalentMeshEndpoint{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("isovalentmeshendpoints").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
