// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	scheme "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// IsovalentBFDProfilesGetter has a method to return a IsovalentBFDProfileInterface.
// A group's client should implement this interface.
type IsovalentBFDProfilesGetter interface {
	IsovalentBFDProfiles() IsovalentBFDProfileInterface
}

// IsovalentBFDProfileInterface has methods to work with IsovalentBFDProfile resources.
type IsovalentBFDProfileInterface interface {
	Create(ctx context.Context, isovalentBFDProfile *v1alpha1.IsovalentBFDProfile, opts v1.CreateOptions) (*v1alpha1.IsovalentBFDProfile, error)
	Update(ctx context.Context, isovalentBFDProfile *v1alpha1.IsovalentBFDProfile, opts v1.UpdateOptions) (*v1alpha1.IsovalentBFDProfile, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.IsovalentBFDProfile, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.IsovalentBFDProfileList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IsovalentBFDProfile, err error)
	IsovalentBFDProfileExpansion
}

// isovalentBFDProfiles implements IsovalentBFDProfileInterface
type isovalentBFDProfiles struct {
	client rest.Interface
}

// newIsovalentBFDProfiles returns a IsovalentBFDProfiles
func newIsovalentBFDProfiles(c *IsovalentV1alpha1Client) *isovalentBFDProfiles {
	return &isovalentBFDProfiles{
		client: c.RESTClient(),
	}
}

// Get takes name of the isovalentBFDProfile, and returns the corresponding isovalentBFDProfile object, and an error if there is any.
func (c *isovalentBFDProfiles) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IsovalentBFDProfile, err error) {
	result = &v1alpha1.IsovalentBFDProfile{}
	err = c.client.Get().
		Resource("isovalentbfdprofiles").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of IsovalentBFDProfiles that match those selectors.
func (c *isovalentBFDProfiles) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IsovalentBFDProfileList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.IsovalentBFDProfileList{}
	err = c.client.Get().
		Resource("isovalentbfdprofiles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested isovalentBFDProfiles.
func (c *isovalentBFDProfiles) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("isovalentbfdprofiles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a isovalentBFDProfile and creates it.  Returns the server's representation of the isovalentBFDProfile, and an error, if there is any.
func (c *isovalentBFDProfiles) Create(ctx context.Context, isovalentBFDProfile *v1alpha1.IsovalentBFDProfile, opts v1.CreateOptions) (result *v1alpha1.IsovalentBFDProfile, err error) {
	result = &v1alpha1.IsovalentBFDProfile{}
	err = c.client.Post().
		Resource("isovalentbfdprofiles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(isovalentBFDProfile).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a isovalentBFDProfile and updates it. Returns the server's representation of the isovalentBFDProfile, and an error, if there is any.
func (c *isovalentBFDProfiles) Update(ctx context.Context, isovalentBFDProfile *v1alpha1.IsovalentBFDProfile, opts v1.UpdateOptions) (result *v1alpha1.IsovalentBFDProfile, err error) {
	result = &v1alpha1.IsovalentBFDProfile{}
	err = c.client.Put().
		Resource("isovalentbfdprofiles").
		Name(isovalentBFDProfile.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(isovalentBFDProfile).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the isovalentBFDProfile and deletes it. Returns an error if one occurs.
func (c *isovalentBFDProfiles) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("isovalentbfdprofiles").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *isovalentBFDProfiles) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("isovalentbfdprofiles").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched isovalentBFDProfile.
func (c *isovalentBFDProfiles) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IsovalentBFDProfile, err error) {
	result = &v1alpha1.IsovalentBFDProfile{}
	err = c.client.Patch(pt).
		Resource("isovalentbfdprofiles").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
