// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	scheme "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// IsovalentPodNetworksGetter has a method to return a IsovalentPodNetworkInterface.
// A group's client should implement this interface.
type IsovalentPodNetworksGetter interface {
	IsovalentPodNetworks() IsovalentPodNetworkInterface
}

// IsovalentPodNetworkInterface has methods to work with IsovalentPodNetwork resources.
type IsovalentPodNetworkInterface interface {
	Create(ctx context.Context, isovalentPodNetwork *v1alpha1.IsovalentPodNetwork, opts v1.CreateOptions) (*v1alpha1.IsovalentPodNetwork, error)
	Update(ctx context.Context, isovalentPodNetwork *v1alpha1.IsovalentPodNetwork, opts v1.UpdateOptions) (*v1alpha1.IsovalentPodNetwork, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.IsovalentPodNetwork, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.IsovalentPodNetworkList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IsovalentPodNetwork, err error)
	IsovalentPodNetworkExpansion
}

// isovalentPodNetworks implements IsovalentPodNetworkInterface
type isovalentPodNetworks struct {
	*gentype.ClientWithList[*v1alpha1.IsovalentPodNetwork, *v1alpha1.IsovalentPodNetworkList]
}

// newIsovalentPodNetworks returns a IsovalentPodNetworks
func newIsovalentPodNetworks(c *IsovalentV1alpha1Client) *isovalentPodNetworks {
	return &isovalentPodNetworks{
		gentype.NewClientWithList[*v1alpha1.IsovalentPodNetwork, *v1alpha1.IsovalentPodNetworkList](
			"isovalentpodnetworks",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v1alpha1.IsovalentPodNetwork { return &v1alpha1.IsovalentPodNetwork{} },
			func() *v1alpha1.IsovalentPodNetworkList { return &v1alpha1.IsovalentPodNetworkList{} }),
	}
}
