name: Verify CuTE sensitive application
description: Verify CuTE sensitive application
runs:
  using: composite
  steps:
    - name: Verify sensitive application pods running
      shell: bash
      run: |
        echo "Verify sensitive application pods running ..."
        kubectl wait --for=condition=ready pod -l zgroup=migrate-svc

    - name: Verify no sensitive application pods restarted
      shell: bash
      run: |
        echo "Verify no sensitive application pods restarted ..."
        for ((i = 5; i >= 1; i--)); do
          restarted=$(kubectl get pods -l zgroup=migrate-svc -o=jsonpath='{range.items[?(@.status.containerStatuses[*].restartCount!=0)]}{.metadata.name}{"\n"}{end}')
          if [[ -n "$restarted" ]]; then
            exit 1
          fi
          echo "no restarts found [$i minutes left ...]"
          sleep 60
        done
        echo "No restarts found."

    - name: Post-test information gathering
      if: ${{ !success() }}
      run: |
        kubectl get pods --all-namespaces -o wide
        cilium status
        cilium sysdump --output-filename cilium-sysdump-out
      shell: bash {0} # Disable default fail-fast behaviour so that all commands run independently

    - name: Upload artifacts
      if: ${{ !success() }}
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      with:
        name: cilium-sysdump-out.zip
        path: cilium-sysdump-out.zip
        retention-days: 5
