{{- if and .Values.preflight.enabled .Values.serviceAccounts.preflight.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: enterprise-cilium-pre-flight
  labels:
    app.kubernetes.io/part-of: cilium
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: enterprise-cilium-pre-flight
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccounts.preflight.name | quote }}
  namespace: {{ .Release.Namespace }}
{{- end }}
