apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    k8s-app: cilium-dnsproxy
  name: cilium-dnsproxy
  namespace: monitoring
spec:
  podMetricsEndpoints:
    - interval: 10s
      port: metrics
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: cilium-dnsproxy
  namespaceSelector:
    any: true