ignore:
  - vex-status: not_affected
  # cilium-agent - the reported issue has not been fixed upstream
  # see https://isovalent.slack.com/archives/C036D1MNKNG/p1727171204828469
  # for more context
  - vulnerability: GHSA-6rqv-5cg7-m4x3
    package:
      location: /usr/bin/cilium-agent
