// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/cilium/cilium/pkg/k8s/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// IsovalentFQDNGroups returns a IsovalentFQDNGroupInformer.
	IsovalentFQDNGroups() IsovalentFQDNGroupInformer
	// IsovalentMeshEndpoints returns a IsovalentMeshEndpointInformer.
	IsovalentMeshEndpoints() IsovalentMeshEndpointInformer
	// IsovalentMulticastGroups returns a IsovalentMulticastGroupInformer.
	IsovalentMulticastGroups() IsovalentMulticastGroupInformer
	// IsovalentMulticastNodes returns a IsovalentMulticastNodeInformer.
	IsovalentMulticastNodes() IsovalentMulticastNodeInformer
	// IsovalentPodNetworks returns a IsovalentPodNetworkInformer.
	IsovalentPodNetworks() IsovalentPodNetworkInformer
	// IsovalentSRv6EgressPolicies returns a IsovalentSRv6EgressPolicyInformer.
	IsovalentSRv6EgressPolicies() IsovalentSRv6EgressPolicyInformer
	// IsovalentSRv6LocatorPools returns a IsovalentSRv6LocatorPoolInformer.
	IsovalentSRv6LocatorPools() IsovalentSRv6LocatorPoolInformer
	// IsovalentSRv6SIDManagers returns a IsovalentSRv6SIDManagerInformer.
	IsovalentSRv6SIDManagers() IsovalentSRv6SIDManagerInformer
	// IsovalentVRFs returns a IsovalentVRFInformer.
	IsovalentVRFs() IsovalentVRFInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// IsovalentFQDNGroups returns a IsovalentFQDNGroupInformer.
func (v *version) IsovalentFQDNGroups() IsovalentFQDNGroupInformer {
	return &isovalentFQDNGroupInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// IsovalentMeshEndpoints returns a IsovalentMeshEndpointInformer.
func (v *version) IsovalentMeshEndpoints() IsovalentMeshEndpointInformer {
	return &isovalentMeshEndpointInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// IsovalentMulticastGroups returns a IsovalentMulticastGroupInformer.
func (v *version) IsovalentMulticastGroups() IsovalentMulticastGroupInformer {
	return &isovalentMulticastGroupInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// IsovalentMulticastNodes returns a IsovalentMulticastNodeInformer.
func (v *version) IsovalentMulticastNodes() IsovalentMulticastNodeInformer {
	return &isovalentMulticastNodeInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// IsovalentPodNetworks returns a IsovalentPodNetworkInformer.
func (v *version) IsovalentPodNetworks() IsovalentPodNetworkInformer {
	return &isovalentPodNetworkInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// IsovalentSRv6EgressPolicies returns a IsovalentSRv6EgressPolicyInformer.
func (v *version) IsovalentSRv6EgressPolicies() IsovalentSRv6EgressPolicyInformer {
	return &isovalentSRv6EgressPolicyInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// IsovalentSRv6LocatorPools returns a IsovalentSRv6LocatorPoolInformer.
func (v *version) IsovalentSRv6LocatorPools() IsovalentSRv6LocatorPoolInformer {
	return &isovalentSRv6LocatorPoolInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// IsovalentSRv6SIDManagers returns a IsovalentSRv6SIDManagerInformer.
func (v *version) IsovalentSRv6SIDManagers() IsovalentSRv6SIDManagerInformer {
	return &isovalentSRv6SIDManagerInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// IsovalentVRFs returns a IsovalentVRFInformer.
func (v *version) IsovalentVRFs() IsovalentVRFInformer {
	return &isovalentVRFInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
