name: Verify CuTE state
description: Verify CuTE state
runs:
  using: composite
  steps:
    - name: Verify conn-disrupt-test
      shell: bash
      run: |
        echo "Verify no conn-disrupt-test pods restarted ..."
        for ((i = 5; i >= 1; i--)); do
          echo "no restarts found [$i minutes left ...]"
          sleep 60
          cilium connectivity test --include-conn-disrupt-test --test no-interrupted-connections --conn-disrupt-test-setup
        done
        echo "No restarts found."
