name: Verify CuTE state
description: Verify CuTE state
inputs:
  cute-dir:
    description: 'Directory with a CuTE code.'
    required: true
  run-tests:
    description: 'Run CuTE tests.'
    required: false
    default: 'true'
runs:
  using: composite
  steps:
    - name: Verify conn-disrupt-test
      shell: bash
      run: |
        echo "Verify no conn-disrupt-test pods restarted ..."
        for ((i = 5; i >= 1; i--)); do
          echo "no restarts found [$i minutes left ...]"
          sleep 60
          cilium connectivity test --include-conn-disrupt-test --test 'no-interrupted-connections,no-ipsec-xfrm-errors' --conn-disrupt-test-setup
        done
        echo "No restarts found."

    - name: Run CuTE tests
      if: inputs.run-tests == 'true'
      working-directory: ./${{ inputs.cute-dir }}
      shell: bash
      run: |
        echo "Running CuTE tests ..."
        make test
