{{- $secretNamespaces := dict -}}
{{- range $cfg := tuple .Values.enterprise.bgpControlPlane -}}
{{- if and $cfg.enabled $cfg.secretsNamespace.create $cfg.secretsNamespace.name -}}
{{- $_ := set $secretNamespaces $cfg.secretsNamespace.name 1 -}}
{{- end -}}
{{- end -}}

{{- range $name, $_ := $secretNamespaces }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $name | quote }}
{{- end}}
