// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// IsovalentBFDNodeConfigListerExpansion allows custom methods to be added to
// IsovalentBFDNodeConfigLister.
type IsovalentBFDNodeConfigListerExpansion interface{}

// IsovalentBFDProfileListerExpansion allows custom methods to be added to
// IsovalentBFDProfileLister.
type IsovalentBFDProfileListerExpansion interface{}

// IsovalentFQDNGroupListerExpansion allows custom methods to be added to
// IsovalentFQDNGroupLister.
type IsovalentFQDNGroupListerExpansion interface{}

// IsovalentMeshEndpointListerExpansion allows custom methods to be added to
// IsovalentMeshEndpointLister.
type IsovalentMeshEndpointListerExpansion interface{}

// IsovalentMeshEndpointNamespaceListerExpansion allows custom methods to be added to
// IsovalentMeshEndpointNamespaceLister.
type IsovalentMeshEndpointNamespaceListerExpansion interface{}

// IsovalentMulticastGroupListerExpansion allows custom methods to be added to
// IsovalentMulticastGroupLister.
type IsovalentMulticastGroupListerExpansion interface{}

// IsovalentMulticastNodeListerExpansion allows custom methods to be added to
// IsovalentMulticastNodeLister.
type IsovalentMulticastNodeListerExpansion interface{}

// IsovalentPodNetworkListerExpansion allows custom methods to be added to
// IsovalentPodNetworkLister.
type IsovalentPodNetworkListerExpansion interface{}

// IsovalentSRv6EgressPolicyListerExpansion allows custom methods to be added to
// IsovalentSRv6EgressPolicyLister.
type IsovalentSRv6EgressPolicyListerExpansion interface{}

// IsovalentSRv6LocatorPoolListerExpansion allows custom methods to be added to
// IsovalentSRv6LocatorPoolLister.
type IsovalentSRv6LocatorPoolListerExpansion interface{}

// IsovalentSRv6SIDManagerListerExpansion allows custom methods to be added to
// IsovalentSRv6SIDManagerLister.
type IsovalentSRv6SIDManagerListerExpansion interface{}

// IsovalentVRFListerExpansion allows custom methods to be added to
// IsovalentVRFLister.
type IsovalentVRFListerExpansion interface{}
