// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// IsovalentMulticastNodeLister helps list IsovalentMulticastNodes.
// All objects returned here must be treated as read-only.
type IsovalentMulticastNodeLister interface {
	// List lists all IsovalentMulticastNodes in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.IsovalentMulticastNode, err error)
	// Get retrieves the IsovalentMulticastNode from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.IsovalentMulticastNode, error)
	IsovalentMulticastNodeListerExpansion
}

// isovalentMulticastNodeLister implements the IsovalentMulticastNodeLister interface.
type isovalentMulticastNodeLister struct {
	indexer cache.Indexer
}

// NewIsovalentMulticastNodeLister returns a new IsovalentMulticastNodeLister.
func NewIsovalentMulticastNodeLister(indexer cache.Indexer) IsovalentMulticastNodeLister {
	return &isovalentMulticastNodeLister{indexer: indexer}
}

// List lists all IsovalentMulticastNodes in the indexer.
func (s *isovalentMulticastNodeLister) List(selector labels.Selector) (ret []*v1alpha1.IsovalentMulticastNode, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.IsovalentMulticastNode))
	})
	return ret, err
}

// Get retrieves the IsovalentMulticastNode from the index for a given name.
func (s *isovalentMulticastNodeLister) Get(name string) (*v1alpha1.IsovalentMulticastNode, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("isovalentmulticastnode"), name)
	}
	return obj.(*v1alpha1.IsovalentMulticastNode), nil
}
