// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// IsovalentBGPNodeConfigOverrideLister helps list IsovalentBGPNodeConfigOverrides.
// All objects returned here must be treated as read-only.
type IsovalentBGPNodeConfigOverrideLister interface {
	// List lists all IsovalentBGPNodeConfigOverrides in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.IsovalentBGPNodeConfigOverride, err error)
	// Get retrieves the IsovalentBGPNodeConfigOverride from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.IsovalentBGPNodeConfigOverride, error)
	IsovalentBGPNodeConfigOverrideListerExpansion
}

// isovalentBGPNodeConfigOverrideLister implements the IsovalentBGPNodeConfigOverrideLister interface.
type isovalentBGPNodeConfigOverrideLister struct {
	indexer cache.Indexer
}

// NewIsovalentBGPNodeConfigOverrideLister returns a new IsovalentBGPNodeConfigOverrideLister.
func NewIsovalentBGPNodeConfigOverrideLister(indexer cache.Indexer) IsovalentBGPNodeConfigOverrideLister {
	return &isovalentBGPNodeConfigOverrideLister{indexer: indexer}
}

// List lists all IsovalentBGPNodeConfigOverrides in the indexer.
func (s *isovalentBGPNodeConfigOverrideLister) List(selector labels.Selector) (ret []*v1alpha1.IsovalentBGPNodeConfigOverride, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.IsovalentBGPNodeConfigOverride))
	})
	return ret, err
}

// Get retrieves the IsovalentBGPNodeConfigOverride from the index for a given name.
func (s *isovalentBGPNodeConfigOverrideLister) Get(name string) (*v1alpha1.IsovalentBGPNodeConfigOverride, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("isovalentbgpnodeconfigoverride"), name)
	}
	return obj.(*v1alpha1.IsovalentBGPNodeConfigOverride), nil
}
