// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// IsovalentBFDNodeConfigOverrideLister helps list IsovalentBFDNodeConfigOverrides.
// All objects returned here must be treated as read-only.
type IsovalentBFDNodeConfigOverrideLister interface {
	// List lists all IsovalentBFDNodeConfigOverrides in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.IsovalentBFDNodeConfigOverride, err error)
	// Get retrieves the IsovalentBFDNodeConfigOverride from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.IsovalentBFDNodeConfigOverride, error)
	IsovalentBFDNodeConfigOverrideListerExpansion
}

// isovalentBFDNodeConfigOverrideLister implements the IsovalentBFDNodeConfigOverrideLister interface.
type isovalentBFDNodeConfigOverrideLister struct {
	indexer cache.Indexer
}

// NewIsovalentBFDNodeConfigOverrideLister returns a new IsovalentBFDNodeConfigOverrideLister.
func NewIsovalentBFDNodeConfigOverrideLister(indexer cache.Indexer) IsovalentBFDNodeConfigOverrideLister {
	return &isovalentBFDNodeConfigOverrideLister{indexer: indexer}
}

// List lists all IsovalentBFDNodeConfigOverrides in the indexer.
func (s *isovalentBFDNodeConfigOverrideLister) List(selector labels.Selector) (ret []*v1alpha1.IsovalentBFDNodeConfigOverride, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.IsovalentBFDNodeConfigOverride))
	})
	return ret, err
}

// Get retrieves the IsovalentBFDNodeConfigOverride from the index for a given name.
func (s *isovalentBFDNodeConfigOverrideLister) Get(name string) (*v1alpha1.IsovalentBFDNodeConfigOverride, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("isovalentbfdnodeconfigoverride"), name)
	}
	return obj.(*v1alpha1.IsovalentBFDNodeConfigOverride), nil
}
