// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// IsovalentBGPNodeConfigLister helps list IsovalentBGPNodeConfigs.
// All objects returned here must be treated as read-only.
type IsovalentBGPNodeConfigLister interface {
	// List lists all IsovalentBGPNodeConfigs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.IsovalentBGPNodeConfig, err error)
	// Get retrieves the IsovalentBGPNodeConfig from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.IsovalentBGPNodeConfig, error)
	IsovalentBGPNodeConfigListerExpansion
}

// isovalentBGPNodeConfigLister implements the IsovalentBGPNodeConfigLister interface.
type isovalentBGPNodeConfigLister struct {
	listers.ResourceIndexer[*v1alpha1.IsovalentBGPNodeConfig]
}

// NewIsovalentBGPNodeConfigLister returns a new IsovalentBGPNodeConfigLister.
func NewIsovalentBGPNodeConfigLister(indexer cache.Indexer) IsovalentBGPNodeConfigLister {
	return &isovalentBGPNodeConfigLister{listers.New[*v1alpha1.IsovalentBGPNodeConfig](indexer, v1alpha1.Resource("isovalentbgpnodeconfig"))}
}
