// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// IsovalentBGPVRFConfigLister helps list IsovalentBGPVRFConfigs.
// All objects returned here must be treated as read-only.
type IsovalentBGPVRFConfigLister interface {
	// List lists all IsovalentBGPVRFConfigs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.IsovalentBGPVRFConfig, err error)
	// Get retrieves the IsovalentBGPVRFConfig from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.IsovalentBGPVRFConfig, error)
	IsovalentBGPVRFConfigListerExpansion
}

// isovalentBGPVRFConfigLister implements the IsovalentBGPVRFConfigLister interface.
type isovalentBGPVRFConfigLister struct {
	indexer cache.Indexer
}

// NewIsovalentBGPVRFConfigLister returns a new IsovalentBGPVRFConfigLister.
func NewIsovalentBGPVRFConfigLister(indexer cache.Indexer) IsovalentBGPVRFConfigLister {
	return &isovalentBGPVRFConfigLister{indexer: indexer}
}

// List lists all IsovalentBGPVRFConfigs in the indexer.
func (s *isovalentBGPVRFConfigLister) List(selector labels.Selector) (ret []*v1alpha1.IsovalentBGPVRFConfig, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.IsovalentBGPVRFConfig))
	})
	return ret, err
}

// Get retrieves the IsovalentBGPVRFConfig from the index for a given name.
func (s *isovalentBGPVRFConfigLister) Get(name string) (*v1alpha1.IsovalentBGPVRFConfig, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("isovalentbgpvrfconfig"), name)
	}
	return obj.(*v1alpha1.IsovalentBGPVRFConfig), nil
}
