// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// IsovalentVRFLister helps list IsovalentVRFs.
// All objects returned here must be treated as read-only.
type IsovalentVRFLister interface {
	// List lists all IsovalentVRFs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.IsovalentVRF, err error)
	// Get retrieves the IsovalentVRF from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.IsovalentVRF, error)
	IsovalentVRFListerExpansion
}

// isovalentVRFLister implements the IsovalentVRFLister interface.
type isovalentVRFLister struct {
	listers.ResourceIndexer[*v1alpha1.IsovalentVRF]
}

// NewIsovalentVRFLister returns a new IsovalentVRFLister.
func NewIsovalentVRFLister(indexer cache.Indexer) IsovalentVRFLister {
	return &isovalentVRFLister{listers.New[*v1alpha1.IsovalentVRF](indexer, v1alpha1.Resource("isovalentvrf"))}
}
