// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// IsovalentVRFLister helps list IsovalentVRFs.
// All objects returned here must be treated as read-only.
type IsovalentVRFLister interface {
	// List lists all IsovalentVRFs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.IsovalentVRF, err error)
	// Get retrieves the IsovalentVRF from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.IsovalentVRF, error)
	IsovalentVRFListerExpansion
}

// isovalentVRFLister implements the IsovalentVRFLister interface.
type isovalentVRFLister struct {
	indexer cache.Indexer
}

// NewIsovalentVRFLister returns a new IsovalentVRFLister.
func NewIsovalentVRFLister(indexer cache.Indexer) IsovalentVRFLister {
	return &isovalentVRFLister{indexer: indexer}
}

// List lists all IsovalentVRFs in the indexer.
func (s *isovalentVRFLister) List(selector labels.Selector) (ret []*v1alpha1.IsovalentVRF, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.IsovalentVRF))
	})
	return ret, err
}

// Get retrieves the IsovalentVRF from the index for a given name.
func (s *isovalentVRFLister) Get(name string) (*v1alpha1.IsovalentVRF, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("isovalentvrf"), name)
	}
	return obj.(*v1alpha1.IsovalentVRF), nil
}
