// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// IsovalentBFDProfileLister helps list IsovalentBFDProfiles.
// All objects returned here must be treated as read-only.
type IsovalentBFDProfileLister interface {
	// List lists all IsovalentBFDProfiles in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.IsovalentBFDProfile, err error)
	// Get retrieves the IsovalentBFDProfile from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.IsovalentBFDProfile, error)
	IsovalentBFDProfileListerExpansion
}

// isovalentBFDProfileLister implements the IsovalentBFDProfileLister interface.
type isovalentBFDProfileLister struct {
	listers.ResourceIndexer[*v1alpha1.IsovalentBFDProfile]
}

// NewIsovalentBFDProfileLister returns a new IsovalentBFDProfileLister.
func NewIsovalentBFDProfileLister(indexer cache.Indexer) IsovalentBFDProfileLister {
	return &isovalentBFDProfileLister{listers.New[*v1alpha1.IsovalentBFDProfile](indexer, v1alpha1.Resource("isovalentbfdprofile"))}
}
