// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// IsovalentMulticastGroupLister helps list IsovalentMulticastGroups.
// All objects returned here must be treated as read-only.
type IsovalentMulticastGroupLister interface {
	// List lists all IsovalentMulticastGroups in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.IsovalentMulticastGroup, err error)
	// Get retrieves the IsovalentMulticastGroup from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.IsovalentMulticastGroup, error)
	IsovalentMulticastGroupListerExpansion
}

// isovalentMulticastGroupLister implements the IsovalentMulticastGroupLister interface.
type isovalentMulticastGroupLister struct {
	indexer cache.Indexer
}

// NewIsovalentMulticastGroupLister returns a new IsovalentMulticastGroupLister.
func NewIsovalentMulticastGroupLister(indexer cache.Indexer) IsovalentMulticastGroupLister {
	return &isovalentMulticastGroupLister{indexer: indexer}
}

// List lists all IsovalentMulticastGroups in the indexer.
func (s *isovalentMulticastGroupLister) List(selector labels.Selector) (ret []*v1alpha1.IsovalentMulticastGroup, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.IsovalentMulticastGroup))
	})
	return ret, err
}

// Get retrieves the IsovalentMulticastGroup from the index for a given name.
func (s *isovalentMulticastGroupLister) Get(name string) (*v1alpha1.IsovalentMulticastGroup, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("isovalentmulticastgroup"), name)
	}
	return obj.(*v1alpha1.IsovalentMulticastGroup), nil
}
