// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// IsovalentBFDProfileLister helps list IsovalentBFDProfiles.
// All objects returned here must be treated as read-only.
type IsovalentBFDProfileLister interface {
	// List lists all IsovalentBFDProfiles in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.IsovalentBFDProfile, err error)
	// Get retrieves the IsovalentBFDProfile from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.IsovalentBFDProfile, error)
	IsovalentBFDProfileListerExpansion
}

// isovalentBFDProfileLister implements the IsovalentBFDProfileLister interface.
type isovalentBFDProfileLister struct {
	indexer cache.Indexer
}

// NewIsovalentBFDProfileLister returns a new IsovalentBFDProfileLister.
func NewIsovalentBFDProfileLister(indexer cache.Indexer) IsovalentBFDProfileLister {
	return &isovalentBFDProfileLister{indexer: indexer}
}

// List lists all IsovalentBFDProfiles in the indexer.
func (s *isovalentBFDProfileLister) List(selector labels.Selector) (ret []*v1alpha1.IsovalentBFDProfile, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.IsovalentBFDProfile))
	})
	return ret, err
}

// Get retrieves the IsovalentBFDProfile from the index for a given name.
func (s *isovalentBFDProfileLister) Get(name string) (*v1alpha1.IsovalentBFDProfile, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("isovalentbfdprofile"), name)
	}
	return obj.(*v1alpha1.IsovalentBFDProfile), nil
}
