// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// IsovalentMulticastGroupLister helps list IsovalentMulticastGroups.
// All objects returned here must be treated as read-only.
type IsovalentMulticastGroupLister interface {
	// List lists all IsovalentMulticastGroups in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.IsovalentMulticastGroup, err error)
	// Get retrieves the IsovalentMulticastGroup from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.IsovalentMulticastGroup, error)
	IsovalentMulticastGroupListerExpansion
}

// isovalentMulticastGroupLister implements the IsovalentMulticastGroupLister interface.
type isovalentMulticastGroupLister struct {
	listers.ResourceIndexer[*v1alpha1.IsovalentMulticastGroup]
}

// NewIsovalentMulticastGroupLister returns a new IsovalentMulticastGroupLister.
func NewIsovalentMulticastGroupLister(indexer cache.Indexer) IsovalentMulticastGroupLister {
	return &isovalentMulticastGroupLister{listers.New[*v1alpha1.IsovalentMulticastGroup](indexer, v1alpha1.Resource("isovalentmulticastgroup"))}
}
