// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// IsovalentBGPNodeConfigOverrideLister helps list IsovalentBGPNodeConfigOverrides.
// All objects returned here must be treated as read-only.
type IsovalentBGPNodeConfigOverrideLister interface {
	// List lists all IsovalentBGPNodeConfigOverrides in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.IsovalentBGPNodeConfigOverride, err error)
	// Get retrieves the IsovalentBGPNodeConfigOverride from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.IsovalentBGPNodeConfigOverride, error)
	IsovalentBGPNodeConfigOverrideListerExpansion
}

// isovalentBGPNodeConfigOverrideLister implements the IsovalentBGPNodeConfigOverrideLister interface.
type isovalentBGPNodeConfigOverrideLister struct {
	listers.ResourceIndexer[*v1alpha1.IsovalentBGPNodeConfigOverride]
}

// NewIsovalentBGPNodeConfigOverrideLister returns a new IsovalentBGPNodeConfigOverrideLister.
func NewIsovalentBGPNodeConfigOverrideLister(indexer cache.Indexer) IsovalentBGPNodeConfigOverrideLister {
	return &isovalentBGPNodeConfigOverrideLister{listers.New[*v1alpha1.IsovalentBGPNodeConfigOverride](indexer, v1alpha1.Resource("isovalentbgpnodeconfigoverride"))}
}
