apiVersion: isovalent.com/v1
kind: IsovalentEgressGatewayPolicy
metadata:
  name: cegp-sample-excluded-cidrs
spec:
  selectors:
  - podSelector:
      matchLabels:
        io.kubernetes.pod.namespace: cilium-test
        kind: client
  destinationCIDRs:
  - 0.0.0.0/0
  excludedCIDRs: # set by the check package in WithIsovalentEgressGatewayPolicy()
  egressGroups: # set by the check package in WithIsovalentEgressGatewayPolicy()
