name: EnterpriseKind

# Any change in triggers needs to be reflected in the concurrency group.
on:
  pull_request:
    paths-ignore:
      - 'Documentation/**'
      - 'test/**'

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after }}
  cancel-in-progress: true

env:
  helm_chart_repo: oci://quay.io/isovalent-charts-dev/cilium
  fqdn_proxy_version: v1.13.2
  # renovate: datasource=github-releases depName=kubernetes-sigs/kind
  kind_version: v0.17.0
  kind_config: .github/kind-config.yaml

jobs:
  installation-and-connectivity:
    name: Installation and connectivity
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          # checkout pull request head ref so that print-chart-version.sh prints the correct chart version.
          ref: ${{ github.event.pull_request.head.ref }}
          # required for git describe
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version-file: 'enterprise/cilium-cli/go.mod'

      - name: Set up job variables
        id: vars
        run: |
          version=$(bash contrib/scripts/print-chart-version.sh)
          echo "version=${version}" >> $GITHUB_OUTPUT
          echo ${version}

      - name: Create kind cluster
        uses: helm/kind-action@d8ccf8fb623ce1bb360ae2f45f323d9d5c5e9f00 # v1.5.0
        with:
          version: ${{ env.kind_version }}
          config: ${{ env.kind_config }}

      - name: Build cilium-cli
        run: |
          cd enterprise/cilium-cli
          go mod tidy
          test -z "$(git status --porcelain)" || (echo "please run 'go mod tidy' and submit your changes"; exit 1)
          make

      - name: Wait for Helm dev chart to be available
        timeout-minutes: 30
        shell: bash
        run: |
          echo ${{ secrets.QUAY_CHARTS_DEV_PASSWORD }} | helm registry login quay.io -u ${{ secrets.QUAY_CHARTS_DEV_USERNAME }} --password-stdin
          until helm pull ${{ env.helm_chart_repo }} --version ${{ steps.vars.outputs.version }}; do sleep 30s; done

      - name: Install Cilium
        run: |
          helm install -n kube-system cilium ${{ env.helm_chart_repo }} --version ${{ steps.vars.outputs.version }} \
          --values .github/values/cilium-enterprise-values.yaml
          kubectl rollout status -n kube-system ds/cilium

      - name: Install FQDN proxy
        run: |
          helm repo add isovalent https://helm.isovalent.com
          helm repo update
          helm install -n kube-system cilium-dnsproxy isovalent/cilium-dnsproxy --version ${{ env.fqdn_proxy_version }} --set prometheus.enabled=true
          kubectl rollout status -n kube-system ds/cilium

      - name: Run enterprise tests
        run: |
          cd enterprise/cilium-cli
          ./cilium version
          ./cilium connectivity test --debug
