name: CuTE CI

on:
  workflow_dispatch:
    inputs:
      PR-number:
        description: "Not relevant for CuTEs."
        required: true
        default: 'n/a'
      context-ref:
        description: "Context branch. More info: https://www.notion.so/isovalent/Customer-Test-Environment-CuTE-43a53c6e2b984c5fb299d7e728ee862f?pvs=4#818708b5a3384e54b21667111cc0423a."
        required: false
        default: ''
      SHA:
        description: "Not relevant for CuTEs."
        required: true
        default: 'n/a'
      extra-args:
        description: "Mandatory arguments passed from the trigger comment via regex capture group. More info: https://www.notion.so/isovalent/Customer-Test-Environment-CuTE-43a53c6e2b984c5fb299d7e728ee862f?pvs=4#818708b5a3384e54b21667111cc0423a."
        required: true
      helm-override-file:
        description: "Helm override Cilium values file."
        required: false
        default: ''

env:
  helm_registry: quay.io
  regions: '{"aws": "us-west-2", "azure": "westus2", "gcp": "us-west2-a"}'
  name: ${{ github.run_id }}
  USE_GKE_GCLOUD_AUTH_PLUGIN: True
  # renovate: datasource=github-releases depName=kubernetes/kubernetes
  kubectl_version: v1.28.1

jobs:
  cute-ci:
    name: CuTE CI
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout workflow context branch
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          persist-credentials: false
          path: workflow-context

      - name: Set Environment Variables
        uses: ./workflow-context/.github/actions/set-env-variables

      - name: Set up job variables
        id: vars
        run: |
          input=${{ inputs.extra-args }}
          upgrade=""
          if [[ $input == *\^* ]]; then
            upgrade="${input##*^}"
            input=${input%%^*}
          fi
          deploy="current"
          if [[ $input == *%* ]]; then
            deploy="${input##*%}"
            input=${input%%%*}
          fi
          region=""
          if [[ $input == *~* ]]; then
            region="${input##*~}"
            input=${input%%~*}
          fi
          ref=""
          if [[ $input == *@* ]]; then
            ref="${input##*@}"
            input=${input%%@*}
          fi
          dir=""
          repo=$input
          if [[ $input == */* ]]; then
            dir="${input##*/}"
            repo=${input%%/*}
          fi

          echo cute_repo=$repo >> $GITHUB_OUTPUT
          echo cute_dir=$dir >> $GITHUB_OUTPUT
          echo cute_ref=$ref >> $GITHUB_OUTPUT
          echo cute_region=$region >> $GITHUB_OUTPUT
          echo deploy_type=$deploy >> $GITHUB_OUTPUT
          echo upgrade_branch=$upgrade >> $GITHUB_OUTPUT

      - name: Checkout CuTE repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: isovalent/cute-${{ steps.vars.outputs.cute_repo }}
          ref: ${{ steps.vars.outputs.cute_ref }}
          token: ${{ secrets.ISOVALENT_BOT_READ_PRIVATE_REPOSITORIES }}
          path: cute

      - name: Set CuTE properties
        id: cute_props
        working-directory: ./cute/${{ steps.vars.outputs.cute_dir }}
        run: |
          echo "getting cloud provider and region ..."
          provider=""
          region=""
          count=$(cat *.tf | grep -c 'provider "aws"' || true)
          if [[ "$count" -gt 0 ]]; then
            provider="aws"
            region=$(echo "$regions" | jq -r .aws)
          fi
          count=$(cat *.tf | grep -c 'provider "azurerm"' || true)
          if [[ "$count" -gt 0 ]]; then
            provider="azure"
            region=$(echo "$regions" | jq -r .azure)
          fi
          count=$(cat *.tf | grep -c 'provider "google"' || true)
          if [[ "$count" -gt 0 ]]; then
            provider="gcp"
            region=$(echo "$regions" | jq -r .gcp)
          fi
          if [[ -z $provider ]]; then
            echo "terraform provider not found!"
            exit 1
          fi
          if [[ "${{ steps.vars.outputs.cute_region }}" != "" ]]; then
            region=${{ steps.vars.outputs.cute_region }}
          fi

          echo "getting helm chart type and version ..."
          is_enterprise_chart=false
          count=$(grep -o '^cilium:\s*$' *.y*ml | wc -l | xargs || true)
          [[ "$count" -gt 0 ]] && is_enterprise_chart=true

          deploy_branch=${{ inputs.context-ref }} # use current branch version by default
          if [[ "${{ steps.vars.outputs.deploy_type }}" == "cute" ]]; then
            deploy_branch=""
          elif [[ "${{ steps.vars.outputs.deploy_type }}" == "stable" ]]; then
            chart_version=$(grep -A 3 '^variable "cilium_helm_version.*" {' *.tf | grep 'default')
            chart_version=$(echo "${chart_version##*=}" | xargs)
            # remove patch version number
            if [[ $chart_version =~ ^[[:digit:]]+.[[:digit:]]+..* ]]; then
              major="${chart_version%%\.*}"
              minor="${chart_version#*.}"
              minor="${minor%%\.*}"
              chart_version="$major.$minor"
            fi
            deploy_branch="v$chart_version${{ env.BRANCH_SUFFIX }}"
          fi

          echo provider=$provider >> $GITHUB_OUTPUT
          echo region=$region >> $GITHUB_OUTPUT
          echo deploy_branch=$deploy_branch >> $GITHUB_OUTPUT
          echo is_enterprise_chart=$is_enterprise_chart >> $GITHUB_OUTPUT

      - name: Print CuTE properties
        run: |
          echo "CuTE repo: ${{ steps.vars.outputs.cute_repo }}"
          echo "CuTE dir: ${{ steps.vars.outputs.cute_dir }}"
          echo "CuTE ref: ${{ steps.vars.outputs.cute_ref }}"
          echo "Cloud provider: ${{ steps.cute_props.outputs.provider }}"
          echo "Region: ${{ steps.cute_props.outputs.region }}"
          echo "Deploy type: ${{ steps.vars.outputs.deploy_type }}"
          echo "Deploy branch: ${{ steps.cute_props.outputs.deploy_branch }}"
          echo "Helm enterprise (umbrella) chart: ${{ steps.cute_props.outputs.is_enterprise_chart }}"
          echo "Helm override file: ${{ inputs.helm-override-file }}"
          echo "Upgrade branch: ${{ steps.vars.outputs.upgrade_branch }}"

      - name: Install Cilium CLI
        run: |
          curl -LO https://github.com/${{ env.CILIUM_CLI_REPO }}/releases/latest/download/cilium-linux-amd64.tar.gz
          sudo tar xzvfC cilium-linux-amd64.tar.gz /usr/local/bin
          rm cilium-linux-amd64.tar.gz

      - name: Install kubectl
        shell: bash
        run: |
          curl -sLO "https://dl.k8s.io/release/${{ env.kubectl_version }}/bin/linux/amd64/kubectl"
          curl -sLO "https://dl.k8s.io/${{ env.kubectl_version }}/bin/linux/amd64/kubectl.sha256"
          echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          kubectl version --client

      - name: Install cfssl
        run: |
          sudo curl -L https://github.com/cloudflare/cfssl/releases/download/v1.6.4/cfssl_1.6.4_linux_amd64 \
               --output /usr/local/bin/cfssl --show-error --fail
          sudo curl -L https://github.com/cloudflare/cfssl/releases/download/v1.6.4/cfssljson_1.6.4_linux_amd64 \
               --output /usr/local/bin/cfssljson --show-error --fail
          sudo chmod +x /usr/local/bin/cfssl*

      # We configure Git SSH to use a private access token so that `terraform
      # get` commands ran as part of `terraform init` are able to download
      # terraform modules from private repositories
      - name: Configure Git
        run: |
          git config --global url."https://oauth2:${{ secrets.ISOVALENT_BOT_READ_PRIVATE_REPOSITORIES }}@github.com".insteadOf ssh://git@github.com

      - name: Set up AWS CLI credentials
        if: steps.cute_props.outputs.provider == 'aws'
        uses: aws-actions/configure-aws-credentials@7ca194810a339d88e7c8d84405d963c9b2b5044f
        with:
          aws-access-key-id: ${{ secrets.AWS_PR_SA_ID }}
          aws-secret-access-key: ${{ secrets.AWS_PR_SA_KEY }}
          aws-region: ${{ steps.cute_props.outputs.region }}

      - name: Set up gcloud credentials
        if: steps.cute_props.outputs.provider == 'gcp'
        id: auth
        uses: google-github-actions/auth@042a3056d60b02f62a368700aaa7a72c9075ff69
        with:
          credentials_json: '${{ secrets.GCP_PR_SA_KEY }}'

      - name: Set up gcloud CLI
        if: steps.cute_props.outputs.provider == 'gcp'
        uses: google-github-actions/setup-gcloud@63496e652100112a8db8a71668b77c67aa1ab071
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Get gcloud user unique id
        if: steps.cute_props.outputs.provider == 'gcp'
        run: |
          GCLOUD_USER_UNIQUE_ID=$(gcloud iam service-accounts describe isovalent-cilium-sa@cilium-pr.iam.gserviceaccount.com --project "${{ secrets.GCP_PROJECT_ID }}" | grep uniqueId | cut -d' ' -f2 | tr -d "'")
          echo "GCLOUD_USER_UNIQUE_ID=$GCLOUD_USER_UNIQUE_ID" >> $GITHUB_ENV

      - name: Install gke-gcloud-auth-plugin
        if: steps.cute_props.outputs.provider == 'gcp'
        run: |
          gcloud components install gke-gcloud-auth-plugin

      - name: Display gcloud CLI info
        if: steps.cute_props.outputs.provider == 'gcp'
        run: |
          gcloud info

      - name: Create an SSH key pair
        if: steps.cute_props.outputs.provider == 'gcp'
        run: |
          ssh-keygen -t rsa -f ${HOME}/.ssh/google_compute_engine -C ${{ env.name }} -b 2048 -N "" -q

      - name: Login to Azure
        if: steps.cute_props.outputs.provider == 'azure'
        uses: azure/login@4c88f01b0e3a5600e08a37889921afd060f75cf0 # v1.5.0
        with:
          creds: ${{ secrets.AZURE_PR_SP_CREDS }}

      - name: Prepare Azure TF variables
        if: steps.cute_props.outputs.provider == 'azure'
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_PR_SP_CREDS }}
        run: |
          # Parse Azure secret into Terraform variables
          echo "ARM_CLIENT_ID=$( jq -r '.clientId' <<< $AZURE_CREDENTIALS )" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=$( jq -r '.clientSecret' <<< $AZURE_CREDENTIALS )" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=$( jq -r '.subscriptionId' <<< $AZURE_CREDENTIALS )" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=$( jq -r '.tenantId' <<< $AZURE_CREDENTIALS )" >> $GITHUB_ENV

      - name: Prepare helm chart
        id: cute_helm
        # `cute` type means that CuTE Helm chart will be used (it already exists)
        if: steps.vars.outputs.deploy_type != 'cute'
        timeout-minutes: 30
        uses: ./workflow-context/.github/actions/cute-helm-chart
        with:
          branch: ${{ steps.cute_props.outputs.deploy_branch }}
          enterprise: ${{ steps.cute_props.outputs.is_enterprise_chart }}
          quay-user: ${{ secrets.QUAY_CHARTS_DEV_USERNAME }}
          quay-password: ${{ secrets.QUAY_CHARTS_DEV_PASSWORD }}
          isovalent-bot: ${{ secrets.ISOVALENT_BOT_READ_PRIVATE_REPOSITORIES }}

      - name: Prepare upgrade helm chart
        id: cute_helm_upgrade
        if: steps.vars.outputs.upgrade_branch != ''
        timeout-minutes: 30
        uses: ./workflow-context/.github/actions/cute-helm-chart
        with:
          branch: ${{ steps.vars.outputs.upgrade_branch }}
          enterprise: ${{ steps.cute_props.outputs.is_enterprise_chart }}
          quay-user: ${{ secrets.QUAY_CHARTS_DEV_USERNAME }}
          quay-password: ${{ secrets.QUAY_CHARTS_DEV_PASSWORD }}
          isovalent-bot: ${{ secrets.ISOVALENT_BOT_READ_PRIVATE_REPOSITORIES }}

      - name: CuTE Terraform variables file
        working-directory: ./cute/${{ steps.vars.outputs.cute_dir }}
        run: |
          cat > terraform.tfvars << EOF
          cluster_name="cute-${{ env.name }}"
          owner="ci"
          region="${{ steps.cute_props.outputs.region }}"
          EOF
          if [[ "${{ steps.vars.outputs.deploy_type }}" != "cute" ]]; then
            HELM_CHART="oci://${{ env.helm_registry }}/${{ env.QUAY_CHARTS_ORGANIZATION_DEV }}/cilium"
            HELM_CHART_VERSION=${{ steps.cute_helm.outputs.version }}
            if [[ ${{ steps.cute_props.outputs.is_enterprise_chart }} == 'true' ]]; then
              HELM_CHART="oci://${{ env.helm_registry }}/${{ env.QUAY_CHARTS_ORGANIZATION_DEV }}/cilium-enterprise"
              HELM_CHART_VERSION=${{ steps.cute_helm.outputs.version-enterprise }}
            fi
            echo "cilium_helm_chart=\"$HELM_CHART\"" >> terraform.tfvars
            echo "cilium_helm_version=\"$HELM_CHART_VERSION\"" >> terraform.tfvars
            # the below variables are for cluster mesh scenario
            echo "cilium_helm_version_1=\"$HELM_CHART_VERSION\"" >> terraform.tfvars
            echo "cilium_helm_version_2=\"$HELM_CHART_VERSION\"" >> terraform.tfvars
          fi
          if [[ "${{ inputs.helm-override-file }}" != "" ]]; then
            echo "cilium_helm_values_override_file_path=\"${{ inputs.helm-override-file }}\"" >> terraform.tfvars
          fi
          if [[ "$ARM_SUBSCRIPTION_ID" != "" ]]; then
            echo "subscription_id=\"$ARM_SUBSCRIPTION_ID\"" >> terraform.tfvars
          fi

      - name: Create CuTE resources
        id: create
        working-directory: ./cute/${{ steps.vars.outputs.cute_dir }}
        run: |
          # The below line is required for Terraform provisioner script:
          # https://github.com/isovalent/terraform-k8s-cilium/blob/main/scripts/provisioner.sh#L79
          helm repo add isovalent https://helm.isovalent.com
          make apply AUTO_APPROVE=true

      - name: Run CuTE tests
        timeout-minutes: 60
        working-directory: ./cute/${{ steps.vars.outputs.cute_dir }}
        run: |
          make test

      # If the creation step was run, always run the cleanup step, even if create or test steps failed
      - name: Clean up CuTE resources
        if: always() && steps.create.outcome != 'skipped'
        working-directory: ./cute/${{ steps.vars.outputs.cute_dir }}
        run: |
          make destroy AUTO_APPROVE=true
